#ifndef __new_layer_infos_control_impl__
#define __new_layer_infos_control_impl__

/**
@file
Subclass of new_layer_infos_control, which is generated by wxFormBuilder.
*/

#include "wxfb/layer_infos_control.h"

/** Implementing new_layer_infos_control */
class layer_infos_control_impl : public layer_infos_control
{
public:
	/** Constructor */
        layer_infos_control_impl( wxWindow* parent );

        virtual void OnOKButtonClick( wxCommandEvent& event ) {Close();}

        friend class layer_control;
};

#endif // __new_layer_infos_control_impl__
