#ifndef __new_layer_infos_control_impl__
#define __new_layer_infos_control_impl__

/**
@file
Subclass of simple_text_window, which is generated by wxFormBuilder.
*/

#include "wxfb/simple_text_window.h"

/** Implementing simple_text_window */
class simple_text_window_impl : public simple_text_window
{
public:
	/** Constructor */
        simple_text_window_impl( wxWindow* parent ) : simple_text_window( parent ) {}

        wxTextCtrl* get_text_control() { return m_text_control; }

        virtual void OnOKButtonClick( wxCommandEvent& event ) {Close();}

        friend class layer_control;
};

#endif // __new_layer_infos_control_impl__
