set( GILVIEWER_PLUGINS_DIR ${PROJECT_BINARY_DIR} )

if(UNIX)
    set( PLUGINS_EXT "so" )
    set( PLUGINS_PRE "lib" )
elseif(WIN32)
    set( PLUGINS_EXT "dll" )
    set( PLUGINS_PRE "" )
endif()

configure_file( ${CMAKE_CURRENT_SOURCE_DIR}/src/GilViewer/config/config_plugins.hpp.cmake.in ${CMAKE_CURRENT_SOURCE_DIR}/src/GilViewer/config/config_plugins.hpp )
include_directories( ${CMAKE_CURRENT_SOURCE_DIR}/src )

message( STATUS "Scanning plugins :" )
file( GLOB list "plugins/*" )
list( SORT list )
foreach( entry ${list} )
  if ( IS_DIRECTORY ${entry} )
    if ( EXISTS ${entry}/CMakeLists.txt )
      message( STATUS "Configuring  ${entry} plugin" )
      add_subdirectory( ${entry} )
    endif()
  endif()
endforeach()
